apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-configmap
data:
  multitool-configmap.port: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <body>
    test
    </body>
    </html>